/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BanosRouteImport } from './routes/banos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as MaterialesRouteImport } from './routes/materiales'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as PisosRevestimientosRouteImport } from './routes/pisos-revestimientos'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as SuperficiesRouteImport } from './routes/superficies'
import { Route as BanosIndexRouteImport } from './routes/banos/index'
import { Route as BanosProductoRouteImport } from './routes/banos/$producto'
import { Route as MesasIndexRouteImport } from './routes/mesas/index'
import { Route as MesasProductoRouteImport } from './routes/mesas/$producto'
import { Route as PisosRevestimientosIndexRouteImport } from './routes/pisos-revestimientos/index'
import { Route as PisosRevestimientosSlugRouteImport } from './routes/pisos-revestimientos/$slug'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos/index'
import { Route as SuperficiesIndexRouteImport } from './routes/superficies/index'
import { Route as SuperficiesMarcaRouteImport } from './routes/superficies/$marca'
import { Route as SuperficiesMarcaIndexRouteImport } from './routes/superficies/$marca/index'
import { Route as SuperficiesMarcaProductoRouteImport } from './routes/superficies/$marca/$producto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BanosRoute = BanosRouteImport.update({
  id: '/banos',
  path: '/banos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialesRoute = MaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const PisosRevestimientosRoute = PisosRevestimientosRouteImport.update({
  id: '/pisos-revestimientos',
  path: '/pisos-revestimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperficiesRoute = SuperficiesRouteImport.update({
  id: '/superficies',
  path: '/superficies',
  getParentRoute: () => rootRouteImport,
} as any)
const BanosIndexRoute = BanosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BanosRoute,
} as any)
const BanosProductoRoute = BanosProductoRouteImport.update({
  id: '/$producto',
  path: '/$producto',
  getParentRoute: () => BanosRoute,
} as any)
const MesasIndexRoute = MesasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MesasRoute,
} as any)
const MesasProductoRoute = MesasProductoRouteImport.update({
  id: '/$producto',
  path: '/$producto',
  getParentRoute: () => MesasRoute,
} as any)
const PisosRevestimientosIndexRoute =
  PisosRevestimientosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PisosRevestimientosRoute,
  } as any)
const PisosRevestimientosSlugRoute = PisosRevestimientosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PisosRevestimientosRoute,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProyectosRoute,
} as any)
const SuperficiesIndexRoute = SuperficiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperficiesRoute,
} as any)
const SuperficiesMarcaRoute = SuperficiesMarcaRouteImport.update({
  id: '/$marca',
  path: '/$marca',
  getParentRoute: () => SuperficiesRoute,
} as any)
const SuperficiesMarcaIndexRoute = SuperficiesMarcaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperficiesMarcaRoute,
} as any)
const SuperficiesMarcaProductoRoute =
  SuperficiesMarcaProductoRouteImport.update({
    id: '/$producto',
    path: '/$producto',
    getParentRoute: () => SuperficiesMarcaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banos': typeof BanosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/materiales': typeof MaterialesRoute
  '/mesas': typeof MesasRouteWithChildren
  '/pisos-revestimientos': typeof PisosRevestimientosRouteWithChildren
  '/proyectos': typeof ProyectosRouteWithChildren
  '/superficies': typeof SuperficiesRouteWithChildren
  '/banos/$producto': typeof BanosProductoRoute
  '/mesas/$producto': typeof MesasProductoRoute
  '/pisos-revestimientos/$slug': typeof PisosRevestimientosSlugRoute
  '/superficies/$marca': typeof SuperficiesMarcaRouteWithChildren
  '/banos/': typeof BanosIndexRoute
  '/mesas/': typeof MesasIndexRoute
  '/pisos-revestimientos/': typeof PisosRevestimientosIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/superficies/': typeof SuperficiesIndexRoute
  '/superficies/$marca/$producto': typeof SuperficiesMarcaProductoRoute
  '/superficies/$marca/': typeof SuperficiesMarcaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/materiales': typeof MaterialesRoute
  '/banos/$producto': typeof BanosProductoRoute
  '/mesas/$producto': typeof MesasProductoRoute
  '/pisos-revestimientos/$slug': typeof PisosRevestimientosSlugRoute
  '/banos': typeof BanosIndexRoute
  '/mesas': typeof MesasIndexRoute
  '/pisos-revestimientos': typeof PisosRevestimientosIndexRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/superficies': typeof SuperficiesIndexRoute
  '/superficies/$marca/$producto': typeof SuperficiesMarcaProductoRoute
  '/superficies/$marca': typeof SuperficiesMarcaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banos': typeof BanosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/materiales': typeof MaterialesRoute
  '/mesas': typeof MesasRouteWithChildren
  '/pisos-revestimientos': typeof PisosRevestimientosRouteWithChildren
  '/proyectos': typeof ProyectosRouteWithChildren
  '/superficies': typeof SuperficiesRouteWithChildren
  '/banos/$producto': typeof BanosProductoRoute
  '/mesas/$producto': typeof MesasProductoRoute
  '/pisos-revestimientos/$slug': typeof PisosRevestimientosSlugRoute
  '/superficies/$marca': typeof SuperficiesMarcaRouteWithChildren
  '/banos/': typeof BanosIndexRoute
  '/mesas/': typeof MesasIndexRoute
  '/pisos-revestimientos/': typeof PisosRevestimientosIndexRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/superficies/': typeof SuperficiesIndexRoute
  '/superficies/$marca/$producto': typeof SuperficiesMarcaProductoRoute
  '/superficies/$marca/': typeof SuperficiesMarcaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banos'
    | '/contacto'
    | '/materiales'
    | '/mesas'
    | '/pisos-revestimientos'
    | '/proyectos'
    | '/superficies'
    | '/banos/$producto'
    | '/mesas/$producto'
    | '/pisos-revestimientos/$slug'
    | '/superficies/$marca'
    | '/banos/'
    | '/mesas/'
    | '/pisos-revestimientos/'
    | '/proyectos/'
    | '/superficies/'
    | '/superficies/$marca/$producto'
    | '/superficies/$marca/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/materiales'
    | '/banos/$producto'
    | '/mesas/$producto'
    | '/pisos-revestimientos/$slug'
    | '/banos'
    | '/mesas'
    | '/pisos-revestimientos'
    | '/proyectos'
    | '/superficies'
    | '/superficies/$marca/$producto'
    | '/superficies/$marca'
  id:
    | '__root__'
    | '/'
    | '/banos'
    | '/contacto'
    | '/materiales'
    | '/mesas'
    | '/pisos-revestimientos'
    | '/proyectos'
    | '/superficies'
    | '/banos/$producto'
    | '/mesas/$producto'
    | '/pisos-revestimientos/$slug'
    | '/superficies/$marca'
    | '/banos/'
    | '/mesas/'
    | '/pisos-revestimientos/'
    | '/proyectos/'
    | '/superficies/'
    | '/superficies/$marca/$producto'
    | '/superficies/$marca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanosRoute: typeof BanosRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  MaterialesRoute: typeof MaterialesRoute
  MesasRoute: typeof MesasRouteWithChildren
  PisosRevestimientosRoute: typeof PisosRevestimientosRouteWithChildren
  ProyectosRoute: typeof ProyectosRouteWithChildren
  SuperficiesRoute: typeof SuperficiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banos': {
      id: '/banos'
      path: '/banos'
      fullPath: '/banos'
      preLoaderRoute: typeof BanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiales': {
      id: '/materiales'
      path: '/materiales'
      fullPath: '/materiales'
      preLoaderRoute: typeof MaterialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pisos-revestimientos': {
      id: '/pisos-revestimientos'
      path: '/pisos-revestimientos'
      fullPath: '/pisos-revestimientos'
      preLoaderRoute: typeof PisosRevestimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superficies': {
      id: '/superficies'
      path: '/superficies'
      fullPath: '/superficies'
      preLoaderRoute: typeof SuperficiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banos/': {
      id: '/banos/'
      path: '/'
      fullPath: '/banos/'
      preLoaderRoute: typeof BanosIndexRouteImport
      parentRoute: typeof BanosRoute
    }
    '/banos/$producto': {
      id: '/banos/$producto'
      path: '/$producto'
      fullPath: '/banos/$producto'
      preLoaderRoute: typeof BanosProductoRouteImport
      parentRoute: typeof BanosRoute
    }
    '/mesas/': {
      id: '/mesas/'
      path: '/'
      fullPath: '/mesas/'
      preLoaderRoute: typeof MesasIndexRouteImport
      parentRoute: typeof MesasRoute
    }
    '/mesas/$producto': {
      id: '/mesas/$producto'
      path: '/$producto'
      fullPath: '/mesas/$producto'
      preLoaderRoute: typeof MesasProductoRouteImport
      parentRoute: typeof MesasRoute
    }
    '/pisos-revestimientos/': {
      id: '/pisos-revestimientos/'
      path: '/'
      fullPath: '/pisos-revestimientos/'
      preLoaderRoute: typeof PisosRevestimientosIndexRouteImport
      parentRoute: typeof PisosRevestimientosRoute
    }
    '/pisos-revestimientos/$slug': {
      id: '/pisos-revestimientos/$slug'
      path: '/$slug'
      fullPath: '/pisos-revestimientos/$slug'
      preLoaderRoute: typeof PisosRevestimientosSlugRouteImport
      parentRoute: typeof PisosRevestimientosRoute
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/superficies/': {
      id: '/superficies/'
      path: '/'
      fullPath: '/superficies/'
      preLoaderRoute: typeof SuperficiesIndexRouteImport
      parentRoute: typeof SuperficiesRoute
    }
    '/superficies/$marca': {
      id: '/superficies/$marca'
      path: '/$marca'
      fullPath: '/superficies/$marca'
      preLoaderRoute: typeof SuperficiesMarcaRouteImport
      parentRoute: typeof SuperficiesRoute
    }
    '/superficies/$marca/': {
      id: '/superficies/$marca/'
      path: '/'
      fullPath: '/superficies/$marca/'
      preLoaderRoute: typeof SuperficiesMarcaIndexRouteImport
      parentRoute: typeof SuperficiesMarcaRoute
    }
    '/superficies/$marca/$producto': {
      id: '/superficies/$marca/$producto'
      path: '/$producto'
      fullPath: '/superficies/$marca/$producto'
      preLoaderRoute: typeof SuperficiesMarcaProductoRouteImport
      parentRoute: typeof SuperficiesMarcaRoute
    }
  }
}

interface BanosRouteChildren {
  BanosProductoRoute: typeof BanosProductoRoute
  BanosIndexRoute: typeof BanosIndexRoute
}

const BanosRouteChildren: BanosRouteChildren = {
  BanosProductoRoute: BanosProductoRoute,
  BanosIndexRoute: BanosIndexRoute,
}

const BanosRouteWithChildren = BanosRoute._addFileChildren(BanosRouteChildren)

interface MesasRouteChildren {
  MesasProductoRoute: typeof MesasProductoRoute
  MesasIndexRoute: typeof MesasIndexRoute
}

const MesasRouteChildren: MesasRouteChildren = {
  MesasProductoRoute: MesasProductoRoute,
  MesasIndexRoute: MesasIndexRoute,
}

const MesasRouteWithChildren = MesasRoute._addFileChildren(MesasRouteChildren)

interface PisosRevestimientosRouteChildren {
  PisosRevestimientosSlugRoute: typeof PisosRevestimientosSlugRoute
  PisosRevestimientosIndexRoute: typeof PisosRevestimientosIndexRoute
}

const PisosRevestimientosRouteChildren: PisosRevestimientosRouteChildren = {
  PisosRevestimientosSlugRoute: PisosRevestimientosSlugRoute,
  PisosRevestimientosIndexRoute: PisosRevestimientosIndexRoute,
}

const PisosRevestimientosRouteWithChildren =
  PisosRevestimientosRoute._addFileChildren(PisosRevestimientosRouteChildren)

interface ProyectosRouteChildren {
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

const ProyectosRouteChildren: ProyectosRouteChildren = {
  ProyectosIndexRoute: ProyectosIndexRoute,
}

const ProyectosRouteWithChildren = ProyectosRoute._addFileChildren(
  ProyectosRouteChildren,
)

interface SuperficiesMarcaRouteChildren {
  SuperficiesMarcaProductoRoute: typeof SuperficiesMarcaProductoRoute
  SuperficiesMarcaIndexRoute: typeof SuperficiesMarcaIndexRoute
}

const SuperficiesMarcaRouteChildren: SuperficiesMarcaRouteChildren = {
  SuperficiesMarcaProductoRoute: SuperficiesMarcaProductoRoute,
  SuperficiesMarcaIndexRoute: SuperficiesMarcaIndexRoute,
}

const SuperficiesMarcaRouteWithChildren =
  SuperficiesMarcaRoute._addFileChildren(SuperficiesMarcaRouteChildren)

interface SuperficiesRouteChildren {
  SuperficiesMarcaRoute: typeof SuperficiesMarcaRouteWithChildren
  SuperficiesIndexRoute: typeof SuperficiesIndexRoute
}

const SuperficiesRouteChildren: SuperficiesRouteChildren = {
  SuperficiesMarcaRoute: SuperficiesMarcaRouteWithChildren,
  SuperficiesIndexRoute: SuperficiesIndexRoute,
}

const SuperficiesRouteWithChildren = SuperficiesRoute._addFileChildren(
  SuperficiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanosRoute: BanosRouteWithChildren,
  ContactoRoute: ContactoRoute,
  MaterialesRoute: MaterialesRoute,
  MesasRoute: MesasRouteWithChildren,
  PisosRevestimientosRoute: PisosRevestimientosRouteWithChildren,
  ProyectosRoute: ProyectosRouteWithChildren,
  SuperficiesRoute: SuperficiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
