/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BanosRouteImport } from './routes/banos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as SuperficiesRouteImport } from './routes/superficies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BanosRoute = BanosRouteImport.update({
  id: '/banos',
  path: '/banos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperficiesRoute = SuperficiesRouteImport.update({
  id: '/superficies',
  path: '/superficies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banos': typeof BanosRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRoute
  '/superficies': typeof SuperficiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banos': typeof BanosRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRoute
  '/superficies': typeof SuperficiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banos': typeof BanosRoute
  '/contacto': typeof ContactoRoute
  '/proyectos': typeof ProyectosRoute
  '/superficies': typeof SuperficiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/banos' | '/contacto' | '/proyectos' | '/superficies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/banos' | '/contacto' | '/proyectos' | '/superficies'
  id: '__root__' | '/' | '/banos' | '/contacto' | '/proyectos' | '/superficies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanosRoute: typeof BanosRoute
  ContactoRoute: typeof ContactoRoute
  ProyectosRoute: typeof ProyectosRoute
  SuperficiesRoute: typeof SuperficiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banos': {
      id: '/banos'
      path: '/banos'
      fullPath: '/banos'
      preLoaderRoute: typeof BanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superficies': {
      id: '/superficies'
      path: '/superficies'
      fullPath: '/superficies'
      preLoaderRoute: typeof SuperficiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanosRoute: BanosRoute,
  ContactoRoute: ContactoRoute,
  ProyectosRoute: ProyectosRoute,
  SuperficiesRoute: SuperficiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
